### ISSUE TITLE
libedit and unicode

### ISSUE THREAD

**Issue by willghatch** [racket/readline#13]
Libedit doesn't seem to handle unicode properly.  Installing the readline-gpl package fixes the issue for me.  Symptoms of using the readline package without installing readline-gpl include `λ` being turned into `Î»`.  Other characters are likewise garbled.

Is this an inherent issue with Libedit?  Or are we doing the FFI wrong in some way?  I think @LeifAndersen did the conversion to use Libedit, so I'm going to defer to your experience on the topic.

**Comment by mflatt** [comment]
It's an inherent issue with libedit. Although libedit recently switch its default build mode to support Unicode, but most installations will have a non-Unicode-enabled libedit.

**Comment by sorawee** [comment]
I think it's OK to close this, now that all issues in racket/racket#3223 are fixed?

**Comment by willghatch** [comment]
> I think it's OK to close this, now that all issues in [racket/racket#3223](https://github.com/racket/racket/issues/3223) are fixed?

That's fine by me.
