### ISSUE TITLE
Make readline dll configurable more conveniently

### ISSUE THREAD

**Issue by elibarzilay** [racket/readline#7]
(This is the same as PR15215, unclear which is better.)

The only thing that "readline-lib.rkt" does is provide a hook for
specifying a library.  The thing is that the hook is searched in only
two places:

1. `(find-user-share-dir)` => which requires installing a package, a
   process that needs to be repeated after every update.  (And
   personally, there's about 0.5% that I'll remember to do that at the
   end of the semester.)

2. `(find-share-dir)`, which AFAICT, is useless since it'll never be
   there assuming that I don't want to hack my installation tree.

It should be very easy to make it try some environment variable that
will have a name for a library to load, which I can then set in my
`.racketrc` or wherever, and not have to worry about it again.

(BTW, this is because my machine does not have the expected libeditline
version, so it barfs.)

**Comment by stamourv** [comment]
When this is closed, so should: http://bugs.racket-lang.org/query/?cmd=view&pr=15215

**Comment by LeifAndersen** [comment]
@elibarzilay Sure. Can you give me an idea about what you would like it to work like?

(Also, as of right now, putting something like this in your `.racketrc` should work:

```
(require setup/dirs)

(let ([readline-path (build-path (find-user-share-dir) "readline-lib.rkt")])
  (unless (file-exists? readline-path)
    (display-to-file #<<EOS
#lang racket
(require ffi/unsafe)
(provide readline-library)
(define readline-library (ffi-lib "libreadline" '("5" "6" "4" "")))
EOS
                     readline-path)))
```
)

**Comment by elibarzilay** [comment]
Just a plain environment variable, so I could add some line like

    export RACKET_READLINE_LIB="/some/path/to/some/library.so"

to my shell configuration.  (Probably not that name though, I think that
usually they have no underlines.)

(And sure, I could do that hack, but hopefully it's obvious why I want
it to be simpler.)

**Comment by LeifAndersen** [comment]
Sure, that works for me. I'll add that change.

> (And sure, I could do that hack, but hopefully it's obvious why I want
it to be simpler.)

Yup, just saying you can do that for now. ;) I'll add the environment variable.

**Comment by elibarzilay** [comment]
I'm set for now, installing the library is not a problem -- the thing that I'm worried about is forgetting that step on the next update, and then doing the whole investigation from scratch.

**Comment by LeifAndersen** [comment]
Okay, I pushed the changes that should fix this issue. You can set PLT_READLINE_LIB to the location of your readline library.

**Comment by elibarzilay** [comment]
Thanks!
