### ISSUE TITLE
libeditline doesn't match fedora installations

### ISSUE THREAD

**Issue by elibarzilay** [racket/readline#8]
(This is the same as PR15216, unclear which is better.)

I have two fedora machines:
1. F20 has `/usr/lib64/libedit.so.0.0.43`
2. F22 has `/usr/lib64/libedit.so.0.0.53`

Neither is found by the new libreadline code.

**Comment by stamourv** [comment]
When this is closed, so should: http://bugs.racket-lang.org/query/?cmd=view&pr=15216

**Comment by LeifAndersen** [comment]
@elibarzilay What version of libedit do you have on your machine?

**Comment by elibarzilay** [comment]
The above two: 0.0.43 and 0.0.53.

**Comment by LeifAndersen** [comment]
Oh, woops, for some reason I misread that for libreadline. Thanks.

**Comment by elibarzilay** [comment]
(To clarify, I have nothing significant that ties me to readline...  My only problem is that editline didn't work, and I don't want to have local hacks for the same reason as the other issue.)

**Comment by LeifAndersen** [comment]
Okay, I have pushed a fix that will hopefully cause racket to find the right library on fedora. I'm not sure though as I don't have a machine to test it.

**Comment by eestrada** [comment]
I made a pull request (#9) that fixes this for Fedora 25. It should potentially fix it for past versions of Fedora as well without needing to resort to hard coding minor dot versions of the libedit library. However, for the sake of safety, I have not removed the old minor dot versions as I haven't had a chance to test against older versions of Fedora yet.

**Comment by LeifAndersen** [comment]
Thank you @eestrada . I have merged in your PR.
